// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

// The dummy_pub package implements the DUMMY_PUB client protocol.
package dummy_pub

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	dcom "github.com/oiweiwei/go-msrpc/msrpc/dcom"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = dcom.GoPackage
)

var (
	// import guard
	GoPackage = "dummy_pub"
)

// DummySubLib class identifier 12345678-1234-1234-1234-123456789abc
var DummySubLibLibraryID = &dcom.ClassID{Data1: 0x12345678, Data2: 0x1234, Data3: 0x1234, Data4: []byte{0x12, 0x34, 0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc}}
