// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package dummysublib

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	dcom "github.com/oiweiwei/go-msrpc/msrpc/dcom"
	dcom_client "github.com/oiweiwei/go-msrpc/msrpc/dcom/client"
	iremunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iremunknown/v0"
	iremunknown2 "github.com/oiweiwei/go-msrpc/msrpc/dcom/iremunknown2/v0"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
	ipublisher "github.com/oiweiwei/midl-gen-go/examples/demo/dummy_pub/dummysublib/ipublisher/v0"
	isubscribersink "github.com/oiweiwei/midl-gen-go/examples/demo/dummy_pub/dummysublib/isubscribersink/v0"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = dcom_client.GoPackage
	_ = dcom.GoPackage
	_ = iremunknown.GoPackage
	_ = iremunknown2.GoPackage
	_ = isubscribersink.GoPackage
	_ = ipublisher.GoPackage
)

var (
	// import guard
	GoPackage = "dummy_pub/dummysublib"
)

// dummy_pub/dummysublib client set.
type Client interface {

	// DCOM common interfaces
	RemoteUnknown() iremunknown.RemoteUnknownClient
	RemoteUnknown2() iremunknown2.RemoteUnknown2Client

	// Package specific interfaces
	ISubscriberSink() isubscribersink.ISubscriberSinkClient
	IPublisher() ipublisher.IPublisherClient
	// AlterContext alters the client context.
	AlterContext(context.Context, ...dcerpc.Option) error

	// Conn returns the client connection (unsafe)
	Conn() dcerpc.Conn

	// IPID sets the object interface identifier.
	IPID(context.Context, *dcom.IPID) Client
}
type xxx_DefaultClient struct {
	cc dcerpc.Conn

	dcomClient dcom_client.Client

	iSubscriberSink isubscribersink.ISubscriberSinkClient
	iPublisher      ipublisher.IPublisherClient
}

func (o *xxx_DefaultClient) RemoteUnknown() iremunknown.RemoteUnknownClient {
	return o.dcomClient.RemoteUnknown()
}

func (o *xxx_DefaultClient) RemoteUnknown2() iremunknown2.RemoteUnknown2Client {
	return o.dcomClient.RemoteUnknown2()
}

func (o *xxx_DefaultClient) ISubscriberSink() isubscribersink.ISubscriberSinkClient {
	return o.iSubscriberSink
}

func (o *xxx_DefaultClient) IPublisher() ipublisher.IPublisherClient {
	return o.iPublisher
}

func NewClient(ctx context.Context, cc dcerpc.Conn, opts ...dcerpc.Option) (Client, error) {

	opts = append(opts,
		dcerpc.WithAbstractSyntax(isubscribersink.ISubscriberSinkSyntaxV0_0),
		dcerpc.WithAbstractSyntax(ipublisher.IPublisherSyntaxV0_0),
		dcerpc.WithAbstractSyntax(iremunknown.RemoteUnknownSyntaxV0_0),
		dcerpc.WithAbstractSyntax(iremunknown2.RemoteUnknown2SyntaxV0_0),
	)

	cc, err := cc.Bind(ctx, opts...)
	if err != nil {
		return nil, err
	}

	o := &xxx_DefaultClient{cc: cc}

	dcomClient, err := dcom_client.NewClient(ctx, cc, append(opts, dcerpc.WithNoBind(cc))...)
	if err != nil {
		return nil, err
	}
	o.dcomClient = dcomClient

	sub, ok := cc.(dcerpc.SubConn)
	if !ok {
		return nil, fmt.Errorf("sub-conn is not supported")
	}

	iSubscriberSinkSubConn, err := sub.SubConn(ctx, isubscribersink.ISubscriberSinkSyntaxV0_0)
	if err != nil {
		// XXX: use main subconnection as a last resort
		// it was noticed that we can reuse the main connection for dcom interfaces
		iSubscriberSinkSubConn = sub
	}

	o.iSubscriberSink, err = isubscribersink.NewISubscriberSinkClient(ctx, iSubscriberSinkSubConn, append(opts, dcerpc.WithNoBind(iSubscriberSinkSubConn))...)

	iPublisherSubConn, err := sub.SubConn(ctx, ipublisher.IPublisherSyntaxV0_0)
	if err != nil {
		// XXX: use main subconnection as a last resort
		// it was noticed that we can reuse the main connection for dcom interfaces
		iPublisherSubConn = sub
	}

	o.iPublisher, err = ipublisher.NewIPublisherClient(ctx, iPublisherSubConn, append(opts, dcerpc.WithNoBind(iPublisherSubConn))...)
	return o, nil
}

func (o *xxx_DefaultClient) AlterContext(ctx context.Context, opts ...dcerpc.Option) error {
	return o.cc.AlterContext(ctx, opts...)
}

func (o *xxx_DefaultClient) Conn() dcerpc.Conn {
	return o.cc
}

func (o *xxx_DefaultClient) IPID(ctx context.Context, ipid *dcom.IPID) Client {
	if ipid == nil {
		ipid = &dcom.IPID{}
	}
	return &xxx_DefaultClient{
		dcomClient:      o.dcomClient.IPID(ctx, ipid),
		iSubscriberSink: o.iSubscriberSink.IPID(ctx, ipid),
		iPublisher:      o.iPublisher.IPID(ctx, ipid),
		cc:              o.cc,
	}
}
