// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package isubscribersink

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = iunknown.GoPackage
)

// ISubscriberSink server interface.
type ISubscriberSinkServer interface {

	// IUnknown base class.
	iunknown.UnknownServer

	// Indicate operation.
	Indicate(context.Context, *IndicateRequest) (*IndicateResponse, error)
}

func RegisterISubscriberSinkServer(conn dcerpc.Conn, o ISubscriberSinkServer, opts ...dcerpc.Option) {
	conn.RegisterServer(NewISubscriberSinkServerHandle(o), append(opts, dcerpc.WithAbstractSyntax(ISubscriberSinkSyntaxV0_0))...)
}

func NewISubscriberSinkServerHandle(o ISubscriberSinkServer) dcerpc.ServerHandle {
	return func(ctx context.Context, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
		return ISubscriberSinkServerHandle(ctx, o, opNum, r)
	}
}

func ISubscriberSinkServerHandle(ctx context.Context, o ISubscriberSinkServer, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
	if opNum < 3 {
		// IUnknown base method.
		return iunknown.UnknownServerHandle(ctx, o, opNum, r)
	}
	switch opNum {
	case 3: // Indicate
		op := &xxx_IndicateOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &IndicateRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.Indicate(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	}
	return nil, nil
}

// Unimplemented ISubscriberSink
type UnimplementedISubscriberSinkServer struct {
	iunknown.UnimplementedUnknownServer
}

func (UnimplementedISubscriberSinkServer) Indicate(context.Context, *IndicateRequest) (*IndicateResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}

var _ ISubscriberSinkServer = (*UnimplementedISubscriberSinkServer)(nil)
