// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package isubscribersink

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	dcom "github.com/oiweiwei/go-msrpc/msrpc/dcom"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	oaut "github.com/oiweiwei/go-msrpc/msrpc/dcom/oaut"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = dcom.GoPackage
	_ = iunknown.GoPackage
	_ = oaut.GoPackage
)

var (
	// import guard
	GoPackage = "dummy_pub/dummysublib"
)

var (
	// ISubscriberSink interface identifier 87654321-4321-4321-4321-abcdef123456
	ISubscriberSinkIID = &dcom.IID{Data1: 0x87654321, Data2: 0x4321, Data3: 0x4321, Data4: []byte{0x43, 0x21, 0xab, 0xcd, 0xef, 0x12, 0x34, 0x56}}
	// Syntax UUID
	ISubscriberSinkSyntaxUUID = &uuid.UUID{TimeLow: 0x87654321, TimeMid: 0x4321, TimeHiAndVersion: 0x4321, ClockSeqHiAndReserved: 0x43, ClockSeqLow: 0x21, Node: [6]uint8{0xab, 0xcd, 0xef, 0x12, 0x34, 0x56}}
	// Syntax ID
	ISubscriberSinkSyntaxV0_0 = &dcerpc.SyntaxID{IfUUID: ISubscriberSinkSyntaxUUID, IfVersionMajor: 0, IfVersionMinor: 0}
)

// ISubscriberSink interface.
type ISubscriberSinkClient interface {

	// IUnknown retrieval method.
	Unknown() iunknown.UnknownClient

	// Indicate operation.
	Indicate(context.Context, *IndicateRequest, ...dcerpc.CallOption) (*IndicateResponse, error)

	// AlterContext alters the client context.
	AlterContext(context.Context, ...dcerpc.Option) error

	// Conn returns the client connection (unsafe)
	Conn() dcerpc.Conn

	// IPID sets the object interface identifier.
	IPID(context.Context, *dcom.IPID) ISubscriberSinkClient
}

type xxx_DefaultISubscriberSinkClient struct {
	iunknown.UnknownClient
	cc   dcerpc.Conn
	ipid *dcom.IPID
}

func (o *xxx_DefaultISubscriberSinkClient) Unknown() iunknown.UnknownClient {
	return o.UnknownClient
}

func (o *xxx_DefaultISubscriberSinkClient) Indicate(ctx context.Context, in *IndicateRequest, opts ...dcerpc.CallOption) (*IndicateResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &IndicateResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return < int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultISubscriberSinkClient) AlterContext(ctx context.Context, opts ...dcerpc.Option) error {
	return o.cc.AlterContext(ctx, opts...)
}

func (o *xxx_DefaultISubscriberSinkClient) Conn() dcerpc.Conn {
	return o.cc
}

func (o *xxx_DefaultISubscriberSinkClient) IPID(ctx context.Context, ipid *dcom.IPID) ISubscriberSinkClient {
	if ipid == nil {
		ipid = &dcom.IPID{}
	}
	return &xxx_DefaultISubscriberSinkClient{
		UnknownClient: o.UnknownClient.IPID(ctx, ipid),
		cc:            o.cc,
		ipid:          ipid,
	}
}

func NewISubscriberSinkClient(ctx context.Context, cc dcerpc.Conn, opts ...dcerpc.Option) (ISubscriberSinkClient, error) {
	var err error
	if !dcom.IsSuperclass(opts) {
		cc, err = cc.Bind(ctx, append(opts, dcerpc.WithAbstractSyntax(ISubscriberSinkSyntaxV0_0))...)
		if err != nil {
			return nil, err
		}
	}
	base, err := iunknown.NewUnknownClient(ctx, cc, append(opts, dcom.Superclass(cc))...)
	if err != nil {
		return nil, err
	}
	ipid, ok := dcom.HasIPID(opts)
	if ok {
		base = base.IPID(ctx, ipid)
	}
	return &xxx_DefaultISubscriberSinkClient{
		UnknownClient: base,
		cc:            cc,
		ipid:          ipid,
	}, nil
}

// xxx_IndicateOperation structure represents the Indicate operation
type xxx_IndicateOperation struct {
	This    *dcom.ORPCThis `idl:"name:This" json:"this"`
	That    *dcom.ORPCThat `idl:"name:That" json:"that"`
	Message *oaut.String   `idl:"name:message" json:"message"`
	Return  int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of Indicate operation.
func (o *xxx_IndicateOperation) OpNum() int { return 3 }

// OpName returns the operation name of Indicate operation.
func (o *xxx_IndicateOperation) OpName() string { return "/ISubscriberSink/v0/Indicate" }

func (o *xxx_IndicateOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_IndicateOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// message {in} (1:{pointer=unique, alias=BSTR}*(1))(2:{pointer=unique, alias=_BSTR, names=FLAGGED_WORD_BLOB}(struct))
	{
		if o.Message != nil {
			_ptr_message := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if o.Message != nil {
					if err := o.Message.MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&oaut.String{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.Message, _ptr_message); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_IndicateOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// message {in} (1:{pointer=unique, alias=BSTR}*(1))(2:{pointer=unique, alias=_BSTR, names=FLAGGED_WORD_BLOB}(struct))
	{
		_ptr_message := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if o.Message == nil {
				o.Message = &oaut.String{}
			}
			if err := o.Message.UnmarshalNDR(ctx, w); err != nil {
				return err
			}
			return nil
		})
		_s_message := func(ptr interface{}) { o.Message = *ptr.(**oaut.String) }
		if err := w.ReadPointer(&o.Message, _s_message, _ptr_message); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_IndicateOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_IndicateOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_IndicateOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// IndicateRequest structure represents the Indicate operation request
type IndicateRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This    *dcom.ORPCThis `idl:"name:This" json:"this"`
	Message *oaut.String   `idl:"name:message" json:"message"`
}

func (o *IndicateRequest) xxx_ToOp(ctx context.Context, op *xxx_IndicateOperation) *xxx_IndicateOperation {
	if op == nil {
		op = &xxx_IndicateOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.Message = o.Message
	return op
}

func (o *IndicateRequest) xxx_FromOp(ctx context.Context, op *xxx_IndicateOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.Message = op.Message
}
func (o *IndicateRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *IndicateRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_IndicateOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeIndicateRequest build a response structure from the given request structure.
func (o *IndicateRequest) MakeResponse() *IndicateResponse {
	return &IndicateResponse{}
}

// OpNum returns the operation number of Indicate operation.
func (o *IndicateRequest) OpNum() int { return 3 }

// OpName returns the operation name of Indicate operation.
func (o *IndicateRequest) OpName() string { return "/ISubscriberSink/v0/Indicate" }

// IndicateResponse structure represents the Indicate operation response
type IndicateResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That *dcom.ORPCThat `idl:"name:That" json:"that"`
	// Return: The Indicate return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *IndicateResponse) xxx_ToOp(ctx context.Context, op *xxx_IndicateOperation) *xxx_IndicateOperation {
	if op == nil {
		op = &xxx_IndicateOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.Return = o.Return
	return op
}

func (o *IndicateResponse) xxx_FromOp(ctx context.Context, op *xxx_IndicateOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.Return = op.Return
}
func (o *IndicateResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *IndicateResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_IndicateOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}
