// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package ipublisher

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = iunknown.GoPackage
)

// IPublisher server interface.
type IPublisherServer interface {

	// IUnknown base class.
	iunknown.UnknownServer

	// Subscribe operation.
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)

	// Unsubscribe operation.
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error)

	// Echo operation.
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
}

func RegisterIPublisherServer(conn dcerpc.Conn, o IPublisherServer, opts ...dcerpc.Option) {
	conn.RegisterServer(NewIPublisherServerHandle(o), append(opts, dcerpc.WithAbstractSyntax(IPublisherSyntaxV0_0))...)
}

func NewIPublisherServerHandle(o IPublisherServer) dcerpc.ServerHandle {
	return func(ctx context.Context, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
		return IPublisherServerHandle(ctx, o, opNum, r)
	}
}

func IPublisherServerHandle(ctx context.Context, o IPublisherServer, opNum int, r ndr.Reader) (dcerpc.Operation, error) {
	if opNum < 3 {
		// IUnknown base method.
		return iunknown.UnknownServerHandle(ctx, o, opNum, r)
	}
	switch opNum {
	case 3: // Subscribe
		op := &xxx_SubscribeOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &SubscribeRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.Subscribe(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 4: // Unsubscribe
		op := &xxx_UnsubscribeOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &UnsubscribeRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.Unsubscribe(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	case 5: // Echo
		op := &xxx_EchoOperation{}
		if err := op.UnmarshalNDRRequest(ctx, r); err != nil {
			return nil, err
		}
		req := &EchoRequest{}
		req.xxx_FromOp(ctx, op)
		resp, err := o.Echo(ctx, req)
		return resp.xxx_ToOp(ctx, op), err
	}
	return nil, nil
}

// Unimplemented IPublisher
type UnimplementedIPublisherServer struct {
	iunknown.UnimplementedUnknownServer
}

func (UnimplementedIPublisherServer) Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedIPublisherServer) Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}
func (UnimplementedIPublisherServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, dcerpc.ErrNotImplemented
}

var _ IPublisherServer = (*UnimplementedIPublisherServer)(nil)
