// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package ipublisher

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	dcom "github.com/oiweiwei/go-msrpc/msrpc/dcom"
	iunknown "github.com/oiweiwei/go-msrpc/msrpc/dcom/iunknown/v0"
	oaut "github.com/oiweiwei/go-msrpc/msrpc/dcom/oaut"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
	dummysublib "github.com/oiweiwei/midl-gen-go/examples/demo/dummy_pub/dummysublib"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = dcom.GoPackage
	_ = iunknown.GoPackage
	_ = dummysublib.GoPackage
	_ = oaut.GoPackage
)

var (
	// import guard
	GoPackage = "dummy_pub/dummysublib"
)

var (
	// IPublisher interface identifier 11111111-2222-3333-4444-555555555555
	IPublisherIID = &dcom.IID{Data1: 0x11111111, Data2: 0x2222, Data3: 0x3333, Data4: []byte{0x44, 0x44, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55}}
	// Syntax UUID
	IPublisherSyntaxUUID = &uuid.UUID{TimeLow: 0x11111111, TimeMid: 0x2222, TimeHiAndVersion: 0x3333, ClockSeqHiAndReserved: 0x44, ClockSeqLow: 0x44, Node: [6]uint8{0x55, 0x55, 0x55, 0x55, 0x55, 0x55}}
	// Syntax ID
	IPublisherSyntaxV0_0 = &dcerpc.SyntaxID{IfUUID: IPublisherSyntaxUUID, IfVersionMajor: 0, IfVersionMinor: 0}
)

// IPublisher interface.
type IPublisherClient interface {

	// IUnknown retrieval method.
	Unknown() iunknown.UnknownClient

	// Subscribe operation.
	Subscribe(context.Context, *SubscribeRequest, ...dcerpc.CallOption) (*SubscribeResponse, error)

	// Unsubscribe operation.
	Unsubscribe(context.Context, *UnsubscribeRequest, ...dcerpc.CallOption) (*UnsubscribeResponse, error)

	// Echo operation.
	Echo(context.Context, *EchoRequest, ...dcerpc.CallOption) (*EchoResponse, error)

	// AlterContext alters the client context.
	AlterContext(context.Context, ...dcerpc.Option) error

	// Conn returns the client connection (unsafe)
	Conn() dcerpc.Conn

	// IPID sets the object interface identifier.
	IPID(context.Context, *dcom.IPID) IPublisherClient
}

type xxx_DefaultIPublisherClient struct {
	iunknown.UnknownClient
	cc   dcerpc.Conn
	ipid *dcom.IPID
}

func (o *xxx_DefaultIPublisherClient) Unknown() iunknown.UnknownClient {
	return o.UnknownClient
}

func (o *xxx_DefaultIPublisherClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...dcerpc.CallOption) (*SubscribeResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &SubscribeResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return < int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultIPublisherClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...dcerpc.CallOption) (*UnsubscribeResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &UnsubscribeResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return < int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultIPublisherClient) Echo(ctx context.Context, in *EchoRequest, opts ...dcerpc.CallOption) (*EchoResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if _, ok := dcom.HasIPID(opts); !ok {
		if o.ipid != nil {
			opts = append(opts, dcom.WithIPID(o.ipid))
		} else {
			return nil, fmt.Errorf("%s: ipid is missing", op.OpName())
		}
	}
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &EchoResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return < int32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultIPublisherClient) AlterContext(ctx context.Context, opts ...dcerpc.Option) error {
	return o.cc.AlterContext(ctx, opts...)
}

func (o *xxx_DefaultIPublisherClient) Conn() dcerpc.Conn {
	return o.cc
}

func (o *xxx_DefaultIPublisherClient) IPID(ctx context.Context, ipid *dcom.IPID) IPublisherClient {
	if ipid == nil {
		ipid = &dcom.IPID{}
	}
	return &xxx_DefaultIPublisherClient{
		UnknownClient: o.UnknownClient.IPID(ctx, ipid),
		cc:            o.cc,
		ipid:          ipid,
	}
}

func NewIPublisherClient(ctx context.Context, cc dcerpc.Conn, opts ...dcerpc.Option) (IPublisherClient, error) {
	var err error
	if !dcom.IsSuperclass(opts) {
		cc, err = cc.Bind(ctx, append(opts, dcerpc.WithAbstractSyntax(IPublisherSyntaxV0_0))...)
		if err != nil {
			return nil, err
		}
	}
	base, err := iunknown.NewUnknownClient(ctx, cc, append(opts, dcom.Superclass(cc))...)
	if err != nil {
		return nil, err
	}
	ipid, ok := dcom.HasIPID(opts)
	if ok {
		base = base.IPID(ctx, ipid)
	}
	return &xxx_DefaultIPublisherClient{
		UnknownClient: base,
		cc:            cc,
		ipid:          ipid,
	}, nil
}

// xxx_SubscribeOperation structure represents the Subscribe operation
type xxx_SubscribeOperation struct {
	This           *dcom.ORPCThis               `idl:"name:This" json:"this"`
	That           *dcom.ORPCThat               `idl:"name:That" json:"that"`
	Sink           *dummysublib.ISubscriberSink `idl:"name:sink" json:"sink"`
	SubscriptionId int32                        `idl:"name:subscriptionId" json:"subscription_id"`
	Return         int32                        `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of Subscribe operation.
func (o *xxx_SubscribeOperation) OpNum() int { return 3 }

// OpName returns the operation name of Subscribe operation.
func (o *xxx_SubscribeOperation) OpName() string { return "/IPublisher/v0/Subscribe" }

func (o *xxx_SubscribeOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_SubscribeOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// sink {in} (1:{pointer=ref}*(1))(2:{alias=ISubscriberSink}(interface))
	{
		if o.Sink != nil {
			_ptr_sink := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if o.Sink != nil {
					if err := o.Sink.MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&dummysublib.ISubscriberSink{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.Sink, _ptr_sink); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_SubscribeOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// sink {in} (1:{pointer=ref}*(1))(2:{alias=ISubscriberSink}(interface))
	{
		_ptr_sink := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if o.Sink == nil {
				o.Sink = &dummysublib.ISubscriberSink{}
			}
			if err := o.Sink.UnmarshalNDR(ctx, w); err != nil {
				return err
			}
			return nil
		})
		_s_sink := func(ptr interface{}) { o.Sink = *ptr.(**dummysublib.ISubscriberSink) }
		if err := w.ReadPointer(&o.Sink, _s_sink, _ptr_sink); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_SubscribeOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_SubscribeOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// subscriptionId {out, retval} (1:{pointer=ref}*(1))(2:{alias=LONG}(int32))
	{
		if err := w.WriteData(o.SubscriptionId); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_SubscribeOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// subscriptionId {out, retval} (1:{pointer=ref}*(1))(2:{alias=LONG}(int32))
	{
		if err := w.ReadData(&o.SubscriptionId); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// SubscribeRequest structure represents the Subscribe operation request
type SubscribeRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This *dcom.ORPCThis               `idl:"name:This" json:"this"`
	Sink *dummysublib.ISubscriberSink `idl:"name:sink" json:"sink"`
}

func (o *SubscribeRequest) xxx_ToOp(ctx context.Context, op *xxx_SubscribeOperation) *xxx_SubscribeOperation {
	if op == nil {
		op = &xxx_SubscribeOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.Sink = o.Sink
	return op
}

func (o *SubscribeRequest) xxx_FromOp(ctx context.Context, op *xxx_SubscribeOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.Sink = op.Sink
}
func (o *SubscribeRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *SubscribeRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_SubscribeOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeSubscribeRequest build a response structure from the given request structure.
func (o *SubscribeRequest) MakeResponse() *SubscribeResponse {
	return &SubscribeResponse{}
}

// OpNum returns the operation number of Subscribe operation.
func (o *SubscribeRequest) OpNum() int { return 3 }

// OpName returns the operation name of Subscribe operation.
func (o *SubscribeRequest) OpName() string { return "/IPublisher/v0/Subscribe" }

// SubscribeResponse structure represents the Subscribe operation response
type SubscribeResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That           *dcom.ORPCThat `idl:"name:That" json:"that"`
	SubscriptionId int32          `idl:"name:subscriptionId" json:"subscription_id"`
	// Return: The Subscribe return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *SubscribeResponse) xxx_ToOp(ctx context.Context, op *xxx_SubscribeOperation) *xxx_SubscribeOperation {
	if op == nil {
		op = &xxx_SubscribeOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.SubscriptionId = o.SubscriptionId
	op.Return = o.Return
	return op
}

func (o *SubscribeResponse) xxx_FromOp(ctx context.Context, op *xxx_SubscribeOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.SubscriptionId = op.SubscriptionId
	o.Return = op.Return
}
func (o *SubscribeResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *SubscribeResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_SubscribeOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_UnsubscribeOperation structure represents the Unsubscribe operation
type xxx_UnsubscribeOperation struct {
	This           *dcom.ORPCThis `idl:"name:This" json:"this"`
	That           *dcom.ORPCThat `idl:"name:That" json:"that"`
	SubscriptionId int32          `idl:"name:subscriptionId" json:"subscription_id"`
	Return         int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of Unsubscribe operation.
func (o *xxx_UnsubscribeOperation) OpNum() int { return 4 }

// OpName returns the operation name of Unsubscribe operation.
func (o *xxx_UnsubscribeOperation) OpName() string { return "/IPublisher/v0/Unsubscribe" }

func (o *xxx_UnsubscribeOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_UnsubscribeOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// subscriptionId {in} (1:{alias=LONG}(int32))
	{
		if err := w.WriteData(o.SubscriptionId); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_UnsubscribeOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// subscriptionId {in} (1:{alias=LONG}(int32))
	{
		if err := w.ReadData(&o.SubscriptionId); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_UnsubscribeOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_UnsubscribeOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_UnsubscribeOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// UnsubscribeRequest structure represents the Unsubscribe operation request
type UnsubscribeRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This           *dcom.ORPCThis `idl:"name:This" json:"this"`
	SubscriptionId int32          `idl:"name:subscriptionId" json:"subscription_id"`
}

func (o *UnsubscribeRequest) xxx_ToOp(ctx context.Context, op *xxx_UnsubscribeOperation) *xxx_UnsubscribeOperation {
	if op == nil {
		op = &xxx_UnsubscribeOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.SubscriptionId = o.SubscriptionId
	return op
}

func (o *UnsubscribeRequest) xxx_FromOp(ctx context.Context, op *xxx_UnsubscribeOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.SubscriptionId = op.SubscriptionId
}
func (o *UnsubscribeRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *UnsubscribeRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_UnsubscribeOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeUnsubscribeRequest build a response structure from the given request structure.
func (o *UnsubscribeRequest) MakeResponse() *UnsubscribeResponse {
	return &UnsubscribeResponse{}
}

// OpNum returns the operation number of Unsubscribe operation.
func (o *UnsubscribeRequest) OpNum() int { return 4 }

// OpName returns the operation name of Unsubscribe operation.
func (o *UnsubscribeRequest) OpName() string { return "/IPublisher/v0/Unsubscribe" }

// UnsubscribeResponse structure represents the Unsubscribe operation response
type UnsubscribeResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That *dcom.ORPCThat `idl:"name:That" json:"that"`
	// Return: The Unsubscribe return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *UnsubscribeResponse) xxx_ToOp(ctx context.Context, op *xxx_UnsubscribeOperation) *xxx_UnsubscribeOperation {
	if op == nil {
		op = &xxx_UnsubscribeOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.Return = o.Return
	return op
}

func (o *UnsubscribeResponse) xxx_FromOp(ctx context.Context, op *xxx_UnsubscribeOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.Return = op.Return
}
func (o *UnsubscribeResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *UnsubscribeResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_UnsubscribeOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// xxx_EchoOperation structure represents the Echo operation
type xxx_EchoOperation struct {
	This   *dcom.ORPCThis `idl:"name:This" json:"this"`
	That   *dcom.ORPCThat `idl:"name:That" json:"that"`
	Input  *oaut.String   `idl:"name:input" json:"input"`
	Output *oaut.String   `idl:"name:output" json:"output"`
	Return int32          `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of Echo operation.
func (o *xxx_EchoOperation) OpNum() int { return 5 }

// OpName returns the operation name of Echo operation.
func (o *xxx_EchoOperation) OpName() string { return "/IPublisher/v0/Echo" }

func (o *xxx_EchoOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_EchoOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This != nil {
			if err := o.This.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThis{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// input {in} (1:{pointer=unique, alias=BSTR}*(1))(2:{pointer=unique, alias=_BSTR, names=FLAGGED_WORD_BLOB}(struct))
	{
		if o.Input != nil {
			_ptr_input := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if o.Input != nil {
					if err := o.Input.MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&oaut.String{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.Input, _ptr_input); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_EchoOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// This {in} (1:{alias=ORPCTHIS}(struct))
	{
		if o.This == nil {
			o.This = &dcom.ORPCThis{}
		}
		if err := o.This.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// input {in} (1:{pointer=unique, alias=BSTR}*(1))(2:{pointer=unique, alias=_BSTR, names=FLAGGED_WORD_BLOB}(struct))
	{
		_ptr_input := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if o.Input == nil {
				o.Input = &oaut.String{}
			}
			if err := o.Input.UnmarshalNDR(ctx, w); err != nil {
				return err
			}
			return nil
		})
		_s_input := func(ptr interface{}) { o.Input = *ptr.(**oaut.String) }
		if err := w.ReadPointer(&o.Input, _s_input, _ptr_input); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_EchoOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_EchoOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That != nil {
			if err := o.That.MarshalNDR(ctx, w); err != nil {
				return err
			}
		} else {
			if err := (&dcom.ORPCThat{}).MarshalNDR(ctx, w); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// output {out, retval} (1:{pointer=ref}*(2))(2:{pointer=unique, alias=BSTR}*(1))(3:{pointer=unique, alias=_BSTR, names=FLAGGED_WORD_BLOB}(struct))
	{
		if o.Output != nil {
			_ptr_output := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if o.Output != nil {
					if err := o.Output.MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&oaut.String{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.Output, _ptr_output); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_EchoOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// That {out} (1:{alias=ORPCTHAT}(struct))
	{
		if o.That == nil {
			o.That = &dcom.ORPCThat{}
		}
		if err := o.That.UnmarshalNDR(ctx, w); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// output {out, retval} (1:{pointer=ref}*(2))(2:{pointer=unique, alias=BSTR}*(1))(3:{pointer=unique, alias=_BSTR, names=FLAGGED_WORD_BLOB}(struct))
	{
		_ptr_output := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if o.Output == nil {
				o.Output = &oaut.String{}
			}
			if err := o.Output.UnmarshalNDR(ctx, w); err != nil {
				return err
			}
			return nil
		})
		_s_output := func(ptr interface{}) { o.Output = *ptr.(**oaut.String) }
		if err := w.ReadPointer(&o.Output, _s_output, _ptr_output); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:{alias=HRESULT, names=LONG}(int32))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// EchoRequest structure represents the Echo operation request
type EchoRequest struct {
	// This: ORPCTHIS structure that is used to send ORPC extension data to the server.
	This  *dcom.ORPCThis `idl:"name:This" json:"this"`
	Input *oaut.String   `idl:"name:input" json:"input"`
}

func (o *EchoRequest) xxx_ToOp(ctx context.Context, op *xxx_EchoOperation) *xxx_EchoOperation {
	if op == nil {
		op = &xxx_EchoOperation{}
	}
	if o == nil {
		return op
	}
	op.This = o.This
	op.Input = o.Input
	return op
}

func (o *EchoRequest) xxx_FromOp(ctx context.Context, op *xxx_EchoOperation) {
	if o == nil {
		return
	}
	o.This = op.This
	o.Input = op.Input
}
func (o *EchoRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *EchoRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_EchoOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeEchoRequest build a response structure from the given request structure.
func (o *EchoRequest) MakeResponse() *EchoResponse {
	return &EchoResponse{}
}

// OpNum returns the operation number of Echo operation.
func (o *EchoRequest) OpNum() int { return 5 }

// OpName returns the operation name of Echo operation.
func (o *EchoRequest) OpName() string { return "/IPublisher/v0/Echo" }

// EchoResponse structure represents the Echo operation response
type EchoResponse struct {
	// That: ORPCTHAT structure that is used to return ORPC extension data to the client.
	That   *dcom.ORPCThat `idl:"name:That" json:"that"`
	Output *oaut.String   `idl:"name:output" json:"output"`
	// Return: The Echo return value.
	Return int32 `idl:"name:Return" json:"return"`
}

func (o *EchoResponse) xxx_ToOp(ctx context.Context, op *xxx_EchoOperation) *xxx_EchoOperation {
	if op == nil {
		op = &xxx_EchoOperation{}
	}
	if o == nil {
		return op
	}
	op.That = o.That
	op.Output = o.Output
	op.Return = o.Return
	return op
}

func (o *EchoResponse) xxx_FromOp(ctx context.Context, op *xxx_EchoOperation) {
	if o == nil {
		return
	}
	o.That = op.That
	o.Output = op.Output
	o.Return = op.Return
}
func (o *EchoResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *EchoResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_EchoOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}
