// Code generated by github.com/oiweiwei/midl-gen-go. DO NOT EDIT.

package my_interface

import (
	"context"
	"fmt"
	"strings"
	"unicode/utf16"

	dcerpc "github.com/oiweiwei/go-msrpc/dcerpc"
	uuid "github.com/oiweiwei/go-msrpc/midl/uuid"
	dtyp "github.com/oiweiwei/go-msrpc/msrpc/dtyp"
	ndr "github.com/oiweiwei/go-msrpc/ndr"
	myidl "github.com/oiweiwei/midl-gen-go/examples/demo/myidl"
)

var (
	_ = context.Background
	_ = fmt.Errorf
	_ = utf16.Encode
	_ = strings.TrimPrefix
	_ = ndr.ZeroString
	_ = (*uuid.UUID)(nil)
	_ = (*dcerpc.SyntaxID)(nil)
	_ = dtyp.GoPackage
	_ = myidl.GoPackage
)

var (
	// import guard
	GoPackage = "myidl"
)

var (
	// Syntax UUID
	MyInterfaceSyntaxUUID = &uuid.UUID{TimeLow: 0x6bffd098, TimeMid: 0xa112, TimeHiAndVersion: 0x3610, ClockSeqHiAndReserved: 0x98, ClockSeqLow: 0x33, Node: [6]uint8{0x1, 0x28, 0x92, 0x2, 0x1, 0x62}}
	// Syntax ID
	MyInterfaceSyntaxV0_0 = &dcerpc.SyntaxID{IfUUID: MyInterfaceSyntaxUUID, IfVersionMajor: 0, IfVersionMinor: 0}
)

// my_interface interface.
type MyInterfaceClient interface {

	// TestCall operation.
	TestCall(context.Context, *TestCallRequest, ...dcerpc.CallOption) (*TestCallResponse, error)

	// TestCall2 operation.
	TestCall2(context.Context, *TestCall2Request, ...dcerpc.CallOption) (*TestCall2Response, error)

	// AlterContext alters the client context.
	AlterContext(context.Context, ...dcerpc.Option) error

	// Conn returns the client connection (unsafe)
	Conn() dcerpc.Conn
}

type xxx_DefaultMyInterfaceClient struct {
	cc dcerpc.Conn
}

func (o *xxx_DefaultMyInterfaceClient) TestCall(ctx context.Context, in *TestCallRequest, opts ...dcerpc.CallOption) (*TestCallResponse, error) {
	op := in.xxx_ToOp(ctx, nil)
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &TestCallResponse{}
	out.xxx_FromOp(ctx, op)
	if op.Return != uint32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultMyInterfaceClient) TestCall2(ctx context.Context, in *TestCall2Request, opts ...dcerpc.CallOption) (*TestCall2Response, error) {
	op := in.xxx_ToOp(ctx, nil)
	if err := o.cc.Invoke(ctx, op, opts...); err != nil {
		return nil, err
	}
	out := &TestCall2Response{}
	out.xxx_FromOp(ctx, op)
	if op.Return != uint32(0) {
		return out, fmt.Errorf("%s: %w", op.OpName(), o.cc.Error(ctx, op.Return))
	}
	return out, nil
}

func (o *xxx_DefaultMyInterfaceClient) AlterContext(ctx context.Context, opts ...dcerpc.Option) error {
	return o.cc.AlterContext(ctx, opts...)
}

func (o *xxx_DefaultMyInterfaceClient) Conn() dcerpc.Conn {
	return o.cc
}

func NewMyInterfaceClient(ctx context.Context, cc dcerpc.Conn, opts ...dcerpc.Option) (MyInterfaceClient, error) {
	cc, err := cc.Bind(ctx, append(opts, dcerpc.WithAbstractSyntax(MyInterfaceSyntaxV0_0))...)
	if err != nil {
		return nil, err
	}
	return &xxx_DefaultMyInterfaceClient{cc: cc}, nil
}

type TestCallNullMask ndr.NullMask

var (
	TestCallNullMaskDwordPointer TestCallNullMask = 1 << 0

	TestCallNullMaskRequestAll  TestCallNullMask = 0 | TestCallNullMaskDwordPointer
	TestCallNullMaskResponseAll TestCallNullMask = 0
)

func (o TestCallNullMask) IsSet(v TestCallNullMask) bool { return o&v != 0 }

func (o TestCallNullMask) Set(v TestCallNullMask) TestCallNullMask { return o | v }

// xxx_TestCallOperation structure represents the TestCall operation
type xxx_TestCallOperation struct {

	// TestCallNullMask is used to carry information on null-valued primitive values.
	NullMask TestCallNullMask

	Input                 string                   `idl:"name:input;string;pointer:unique" json:"input"`
	Input2                *dtyp.UnicodeString      `idl:"name:input2;pointer:unique" json:"input2"`
	Output                string                   `idl:"name:output;string;pointer:unique" json:"output"`
	DwordPointer          uint32                   `idl:"name:dword_pointer;pointer:unique" json:"dword_pointer"`
	MyStructOutput        *myidl.MyInterfaceStruct `idl:"name:my_struct_output;pointer:unique" json:"my_struct_output"`
	MyUnicodeStringOutput *myidl.MyUnicodeString   `idl:"name:my_unicode_string_output;pointer:unique" json:"my_unicode_string_output"`
	Return                uint32                   `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of TestCall operation.
func (o *xxx_TestCallOperation) OpNum() int { return 0 }

// OpName returns the operation name of TestCall operation.
func (o *xxx_TestCallOperation) OpName() string { return "/my_interface/v0/TestCall" }

func (o *xxx_TestCallOperation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_TestCallOperation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// input {in} (1:{string, pointer=unique}*(1)[dim:0,string,null](wchar))
	{
		if o.Input != "" {
			_ptr_input := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if err := ndr.WriteUTF16NString(ctx, w, o.Input); err != nil {
					return err
				}
				return nil
			})
			if err := w.WritePointer(&o.Input, _ptr_input); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// input2 {in} (1:{pointer=unique, alias=PRPC_UNICODE_STRING}*(1))(2:{alias=RPC_UNICODE_STRING}(struct))
	{
		if o.Input2 != nil {
			_ptr_input2 := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if o.Input2 != nil {
					if err := o.Input2.MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&dtyp.UnicodeString{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.Input2, _ptr_input2); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// dword_pointer {in} (1:{pointer=unique}*(1))(2:{alias=DWORD}(uint32))
	{
		if o.NullMask&TestCallNullMaskDwordPointer == 0 {
			_ptr_dword_pointer := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if err := w.WriteData(o.DwordPointer); err != nil {
					return err
				}
				return nil
			})
			if err := w.WritePointer(&o.DwordPointer, _ptr_dword_pointer); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_TestCallOperation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// input {in} (1:{string, pointer=unique}*(1)[dim:0,string,null](wchar))
	{
		_ptr_input := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if err := ndr.ReadUTF16NString(ctx, w, &o.Input); err != nil {
				return err
			}
			return nil
		})
		_s_input := func(ptr interface{}) { o.Input = *ptr.(*string) }
		if err := w.ReadPointer(&o.Input, _s_input, _ptr_input); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// input2 {in} (1:{pointer=unique, alias=PRPC_UNICODE_STRING}*(1))(2:{alias=RPC_UNICODE_STRING}(struct))
	{
		_ptr_input2 := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if o.Input2 == nil {
				o.Input2 = &dtyp.UnicodeString{}
			}
			if err := o.Input2.UnmarshalNDR(ctx, w); err != nil {
				return err
			}
			return nil
		})
		_s_input2 := func(ptr interface{}) { o.Input2 = *ptr.(**dtyp.UnicodeString) }
		if err := w.ReadPointer(&o.Input2, _s_input2, _ptr_input2); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// dword_pointer {in} (1:{pointer=unique}*(1))(2:{alias=DWORD}(uint32))
	{
		_ptr_dword_pointer := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if err := w.ReadData(&o.DwordPointer); err != nil {
				return err
			}
			return nil
		})
		_s_dword_pointer := func(ptr interface{}) { o.DwordPointer = *ptr.(*uint32) }
		_m_dword_pointer := func() { o.NullMask |= TestCallNullMaskDwordPointer }
		if err := w.ReadPointerWithHook(&o.DwordPointer, ndr.PointerHook{_s_dword_pointer, _m_dword_pointer}, _ptr_dword_pointer); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_TestCallOperation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_TestCallOperation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// output {out} (1:{string, pointer=unique}*(1)[dim:0,string,null](wchar))
	{
		if o.Output != "" {
			_ptr_output := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if err := ndr.WriteUTF16NString(ctx, w, o.Output); err != nil {
					return err
				}
				return nil
			})
			if err := w.WritePointer(&o.Output, _ptr_output); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// my_struct_output {out} (1:{pointer=unique, alias=PMY_INTERFACE_STRUCT}*(1))(2:{alias=MY_INTERFACE_STRUCT}(struct))
	{
		if o.MyStructOutput != nil {
			_ptr_my_struct_output := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if o.MyStructOutput != nil {
					if err := o.MyStructOutput.MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&myidl.MyInterfaceStruct{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.MyStructOutput, _ptr_my_struct_output); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// my_unicode_string_output {out} (1:{pointer=unique, alias=PMY_UNICODE_STRING}*(1))(2:{alias=MY_UNICODE_STRING, names=RPC_UNICODE_STRING}(struct))
	{
		if o.MyUnicodeStringOutput != nil {
			_ptr_my_unicode_string_output := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if o.MyUnicodeStringOutput != nil {
					if err := o.MyUnicodeStringOutput.MarshalNDR(ctx, w); err != nil {
						return err
					}
				} else {
					if err := (&myidl.MyUnicodeString{}).MarshalNDR(ctx, w); err != nil {
						return err
					}
				}
				return nil
			})
			if err := w.WritePointer(&o.MyUnicodeStringOutput, _ptr_my_unicode_string_output); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:(error_status_t))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_TestCallOperation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// output {out} (1:{string, pointer=unique}*(1)[dim:0,string,null](wchar))
	{
		_ptr_output := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if err := ndr.ReadUTF16NString(ctx, w, &o.Output); err != nil {
				return err
			}
			return nil
		})
		_s_output := func(ptr interface{}) { o.Output = *ptr.(*string) }
		if err := w.ReadPointer(&o.Output, _s_output, _ptr_output); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// my_struct_output {out} (1:{pointer=unique, alias=PMY_INTERFACE_STRUCT}*(1))(2:{alias=MY_INTERFACE_STRUCT}(struct))
	{
		_ptr_my_struct_output := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if o.MyStructOutput == nil {
				o.MyStructOutput = &myidl.MyInterfaceStruct{}
			}
			if err := o.MyStructOutput.UnmarshalNDR(ctx, w); err != nil {
				return err
			}
			return nil
		})
		_s_my_struct_output := func(ptr interface{}) { o.MyStructOutput = *ptr.(**myidl.MyInterfaceStruct) }
		if err := w.ReadPointer(&o.MyStructOutput, _s_my_struct_output, _ptr_my_struct_output); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// my_unicode_string_output {out} (1:{pointer=unique, alias=PMY_UNICODE_STRING}*(1))(2:{alias=MY_UNICODE_STRING, names=RPC_UNICODE_STRING}(struct))
	{
		_ptr_my_unicode_string_output := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if o.MyUnicodeStringOutput == nil {
				o.MyUnicodeStringOutput = &myidl.MyUnicodeString{}
			}
			if err := o.MyUnicodeStringOutput.UnmarshalNDR(ctx, w); err != nil {
				return err
			}
			return nil
		})
		_s_my_unicode_string_output := func(ptr interface{}) { o.MyUnicodeStringOutput = *ptr.(**myidl.MyUnicodeString) }
		if err := w.ReadPointer(&o.MyUnicodeStringOutput, _s_my_unicode_string_output, _ptr_my_unicode_string_output); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	// Return {out} (1:(error_status_t))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// TestCallRequest structure represents the TestCall operation request
type TestCallRequest struct {

	// TestCallNullMask is used to carry information on null-valued primitive values.
	NullMask TestCallNullMask

	Input        string              `idl:"name:input;string;pointer:unique" json:"input"`
	Input2       *dtyp.UnicodeString `idl:"name:input2;pointer:unique" json:"input2"`
	DwordPointer uint32              `idl:"name:dword_pointer;pointer:unique" json:"dword_pointer"`
}

func (o *TestCallRequest) xxx_ToOp(ctx context.Context, op *xxx_TestCallOperation) *xxx_TestCallOperation {
	if op == nil {
		op = &xxx_TestCallOperation{}
	}
	if o == nil {
		return op
	}
	op.Input = o.Input
	op.Input2 = o.Input2
	op.DwordPointer = o.DwordPointer
	op.NullMask = o.NullMask
	return op
}

func (o *TestCallRequest) xxx_FromOp(ctx context.Context, op *xxx_TestCallOperation) {
	if o == nil {
		return
	}
	o.Input = op.Input
	o.Input2 = op.Input2
	o.DwordPointer = op.DwordPointer
	o.NullMask = TestCallNullMask(op.NullMask) & TestCallNullMaskRequestAll
}
func (o *TestCallRequest) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *TestCallRequest) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_TestCallOperation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeTestCallRequest build a response structure from the given request structure.
func (o *TestCallRequest) MakeResponse() *TestCallResponse {
	return &TestCallResponse{}
}

// OpNum returns the operation number of TestCall operation.
func (o *TestCallRequest) OpNum() int { return 0 }

// OpName returns the operation name of TestCall operation.
func (o *TestCallRequest) OpName() string { return "/my_interface/v0/TestCall" }

// TestCallResponse structure represents the TestCall operation response
type TestCallResponse struct {

	// TestCallNullMask is used to carry information on null-valued primitive values.
	NullMask TestCallNullMask

	Output                string                   `idl:"name:output;string;pointer:unique" json:"output"`
	MyStructOutput        *myidl.MyInterfaceStruct `idl:"name:my_struct_output;pointer:unique" json:"my_struct_output"`
	MyUnicodeStringOutput *myidl.MyUnicodeString   `idl:"name:my_unicode_string_output;pointer:unique" json:"my_unicode_string_output"`
	// Return: The TestCall return value.
	Return uint32 `idl:"name:Return" json:"return"`
}

func (o *TestCallResponse) xxx_ToOp(ctx context.Context, op *xxx_TestCallOperation) *xxx_TestCallOperation {
	if op == nil {
		op = &xxx_TestCallOperation{}
	}
	if o == nil {
		return op
	}
	op.Output = o.Output
	op.MyStructOutput = o.MyStructOutput
	op.MyUnicodeStringOutput = o.MyUnicodeStringOutput
	op.Return = o.Return
	op.NullMask = o.NullMask
	return op
}

func (o *TestCallResponse) xxx_FromOp(ctx context.Context, op *xxx_TestCallOperation) {
	if o == nil {
		return
	}
	o.Output = op.Output
	o.MyStructOutput = op.MyStructOutput
	o.MyUnicodeStringOutput = op.MyUnicodeStringOutput
	o.Return = op.Return
	o.NullMask = TestCallNullMask(op.NullMask) & TestCallNullMaskResponseAll
}
func (o *TestCallResponse) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *TestCallResponse) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_TestCallOperation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

type TestCall2NullMask ndr.NullMask

var (
	TestCall2NullMaskDwordPointer TestCall2NullMask = 1 << 0

	TestCall2NullMaskRequestAll  TestCall2NullMask = 0 | TestCall2NullMaskDwordPointer
	TestCall2NullMaskResponseAll TestCall2NullMask = 0
)

func (o TestCall2NullMask) IsSet(v TestCall2NullMask) bool { return o&v != 0 }

func (o TestCall2NullMask) Set(v TestCall2NullMask) TestCall2NullMask { return o | v }

// xxx_TestCall2Operation structure represents the TestCall2 operation
type xxx_TestCall2Operation struct {

	// TestCall2NullMask is used to carry information on null-valued primitive values.
	NullMask TestCall2NullMask

	NoPointer    uint32 `idl:"name:no_pointer;pointer:ref" json:"no_pointer"`
	DwordPointer uint32 `idl:"name:dword_pointer;pointer:unique" json:"dword_pointer"`
	Return       uint32 `idl:"name:Return" json:"return"`
}

// OpNum returns the operation number of TestCall2 operation.
func (o *xxx_TestCall2Operation) OpNum() int { return 1 }

// OpName returns the operation name of TestCall2 operation.
func (o *xxx_TestCall2Operation) OpName() string { return "/my_interface/v0/TestCall2" }

func (o *xxx_TestCall2Operation) xxx_PrepareRequestPayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareRequestPayload(context.Context) error }); ok {
		if err := hook.AfterPrepareRequestPayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_TestCall2Operation) MarshalNDRRequest(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareRequestPayload(ctx); err != nil {
		return err
	}
	// no_pointer {in} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.WriteData(o.NoPointer); err != nil {
			return err
		}
	}
	// dword_pointer {in} (1:{pointer=unique}*(1))(2:{alias=DWORD}(uint32))
	{
		if o.NullMask&TestCall2NullMaskDwordPointer == 0 {
			_ptr_dword_pointer := ndr.MarshalNDRFunc(func(ctx context.Context, w ndr.Writer) error {
				if err := w.WriteData(o.DwordPointer); err != nil {
					return err
				}
				return nil
			})
			if err := w.WritePointer(&o.DwordPointer, _ptr_dword_pointer); err != nil {
				return err
			}
		} else {
			if err := w.WritePointer(nil); err != nil {
				return err
			}
		}
		if err := w.WriteDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_TestCall2Operation) UnmarshalNDRRequest(ctx context.Context, w ndr.Reader) error {
	// no_pointer {in} (1:{pointer=ref}*(1))(2:{alias=DWORD}(uint32))
	{
		if err := w.ReadData(&o.NoPointer); err != nil {
			return err
		}
	}
	// dword_pointer {in} (1:{pointer=unique}*(1))(2:{alias=DWORD}(uint32))
	{
		_ptr_dword_pointer := ndr.UnmarshalNDRFunc(func(ctx context.Context, w ndr.Reader) error {
			if err := w.ReadData(&o.DwordPointer); err != nil {
				return err
			}
			return nil
		})
		_s_dword_pointer := func(ptr interface{}) { o.DwordPointer = *ptr.(*uint32) }
		_m_dword_pointer := func() { o.NullMask |= TestCall2NullMaskDwordPointer }
		if err := w.ReadPointerWithHook(&o.DwordPointer, ndr.PointerHook{_s_dword_pointer, _m_dword_pointer}, _ptr_dword_pointer); err != nil {
			return err
		}
		if err := w.ReadDeferred(); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_TestCall2Operation) xxx_PrepareResponsePayload(ctx context.Context) error {
	if hook, ok := (interface{})(o).(interface{ AfterPrepareResponsePayload(context.Context) error }); ok {
		if err := hook.AfterPrepareResponsePayload(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_TestCall2Operation) MarshalNDRResponse(ctx context.Context, w ndr.Writer) error {
	if err := o.xxx_PrepareResponsePayload(ctx); err != nil {
		return err
	}
	// Return {out} (1:(error_status_t))
	{
		if err := w.WriteData(o.Return); err != nil {
			return err
		}
	}
	return nil
}

func (o *xxx_TestCall2Operation) UnmarshalNDRResponse(ctx context.Context, w ndr.Reader) error {
	// Return {out} (1:(error_status_t))
	{
		if err := w.ReadData(&o.Return); err != nil {
			return err
		}
	}
	return nil
}

// TestCall2Request structure represents the TestCall2 operation request
type TestCall2Request struct {

	// TestCall2NullMask is used to carry information on null-valued primitive values.
	NullMask TestCall2NullMask

	NoPointer    uint32 `idl:"name:no_pointer;pointer:ref" json:"no_pointer"`
	DwordPointer uint32 `idl:"name:dword_pointer;pointer:unique" json:"dword_pointer"`
}

func (o *TestCall2Request) xxx_ToOp(ctx context.Context, op *xxx_TestCall2Operation) *xxx_TestCall2Operation {
	if op == nil {
		op = &xxx_TestCall2Operation{}
	}
	if o == nil {
		return op
	}
	op.NoPointer = o.NoPointer
	op.DwordPointer = o.DwordPointer
	op.NullMask = o.NullMask
	return op
}

func (o *TestCall2Request) xxx_FromOp(ctx context.Context, op *xxx_TestCall2Operation) {
	if o == nil {
		return
	}
	o.NoPointer = op.NoPointer
	o.DwordPointer = op.DwordPointer
	o.NullMask = TestCall2NullMask(op.NullMask) & TestCall2NullMaskRequestAll
}
func (o *TestCall2Request) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRRequest(ctx, w)
}
func (o *TestCall2Request) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_TestCall2Operation{}
	if err := _o.UnmarshalNDRRequest(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}

// MakeTestCall2Request build a response structure from the given request structure.
func (o *TestCall2Request) MakeResponse() *TestCall2Response {
	return &TestCall2Response{}
}

// OpNum returns the operation number of TestCall2 operation.
func (o *TestCall2Request) OpNum() int { return 1 }

// OpName returns the operation name of TestCall2 operation.
func (o *TestCall2Request) OpName() string { return "/my_interface/v0/TestCall2" }

// TestCall2Response structure represents the TestCall2 operation response
type TestCall2Response struct {

	// TestCall2NullMask is used to carry information on null-valued primitive values.
	NullMask TestCall2NullMask

	// Return: The TestCall2 return value.
	Return uint32 `idl:"name:Return" json:"return"`
}

func (o *TestCall2Response) xxx_ToOp(ctx context.Context, op *xxx_TestCall2Operation) *xxx_TestCall2Operation {
	if op == nil {
		op = &xxx_TestCall2Operation{}
	}
	if o == nil {
		return op
	}
	op.Return = o.Return
	op.NullMask = o.NullMask
	return op
}

func (o *TestCall2Response) xxx_FromOp(ctx context.Context, op *xxx_TestCall2Operation) {
	if o == nil {
		return
	}
	o.Return = op.Return
	o.NullMask = TestCall2NullMask(op.NullMask) & TestCall2NullMaskResponseAll
}
func (o *TestCall2Response) MarshalNDR(ctx context.Context, w ndr.Writer) error {
	return o.xxx_ToOp(ctx, nil).MarshalNDRResponse(ctx, w)
}
func (o *TestCall2Response) UnmarshalNDR(ctx context.Context, r ndr.Reader) error {
	_o := &xxx_TestCall2Operation{}
	if err := _o.UnmarshalNDRResponse(ctx, r); err != nil {
		return err
	}
	o.xxx_FromOp(ctx, _o)
	return nil
}
